# 工作流名称
name: Sync-TrivyDB-Images
# 工作流运行时显示名称
run-name: ${{ github.actor }} is Sync Images to MyRegistry.
# 怎样触发工作流
on:
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# 工作流程任务（通常含有一个或多个步骤）
jobs:
  syncimages:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repos
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.9.1

    - name: Login to Docker Hub
      uses: docker/login-action@v2.2.0
      with:
        registry: "convertlab.tencentcloudcr.com"
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        logout: false
        
    - name: Use Skopeo Tools Sync Image to MyRegistry
      env:
        SRC_IMAGE: "ghcr.io/aquasecurity/trivy-db:2"
        DST_IMAGE: "convertlab.tencentcloudcr.com/rdc/coach:trivy-db"
      run: |
        #!/usr/bin/env bash
        skopeo copy docker://ghcr.io/aquasecurity/trivy-db:2 docker://convertlab.tencentcloudcr.com/rdc/coach:trivy-db
        skopeo copy docker://ghcr.m.daocloud.io/aquasecurity/trivy-java-db:1 docker://convertlab.tencentcloudcr.com/rdc/coach:trivy-java-db
 
